#!/bin/bash
# Script to change background selecting a random file(image) as back
# background image
#wallpaper_dir_path=~/wallpapers
wallpaper_dir_path=/media/shadowthrone/seven_cities/wallpapers/
file_path="dsfadsf "
theme_folder="*"
bus_address=
get_dbus_address(){
    if [ ! -z $DBUS_SESSION_BUS_ADDRESS ]; then
        session_pid=$(pgrep "mate-session" -u "shadowthrone")
        exp=$(cat /proc/$session_pid/environ | grep -z "^DBUS_SESSION_BUS_ADDRESS=")
        #DBUS_SESSION_BUS_ADDRESS="$exp"
        export "$exp"
        echo $bus_address
    fi
}
### echo "The randomly-selected file is: $path"
validate_dir(){
    if [ ! -d "$1" ]; then
        echo "The '$1' folder does not exist" 1>&2
        exit 1
    fi
}
# get_random_theme(){
#     while [ ! -f $file_path ]; do
#         file_path=$(locate "$wallpaper_dir_path/*" | sort --random-sort | head --lines=1)
#     done
# }

get_random_theme(){
    file_path=$(find $wallpaper_dir_path -type f  | sort --random-sort | head --lines=1)
}

usage(){
    echo "Syntaxis: "
    printf "\t %s \n" "$(basename $0) [theme_folder]"
}

####### Main ########
get_dbus_address
echo "Outside Function:" $bus_address
export $bus_address

validate_dir "$wallpaper_dir_path"
case $# in
    0) get_random_theme
        ;;
    1)  theme_folder="$1"
        wallpaper_dir_path="$wallpaper_dir_path/$theme_folder"
        validate_dir "$wallpaper_dir_path"
        get_random_theme
        ;;
    *) usage
        exit 1
        ;;
esac
gsettings set org.mate.background picture-filename "$file_path"  
echo "Selected image: $file_path"
