#!/bin/bash
# Script to change background selecting a random file(image) as back
# background image
#wallpaper_dir_path=~/wallpapers
test_img='/media/shadowthrone/seven_cities/wallpapers/Halo_4/2_halo4.jpg'
wallpaper_dir_path=/media/shadowthrone/seven_cities/wallpapers/
file_path="dsfadsf "
theme_folder="*"
bus_address=
### GSettings configurations
schema=""
key=""
key_prefix=""
## TODO: cinnamon schema need an URI with a protocol prefix like file:// or so
## need to see if mate's schema works with this protocol or maybe I will have to
## add a 'protocol' variable or 'prefix' for the image name/URI
set_schema_key(){
    case "$DESKTOP_SESSION" in
        mate) 
            echo "Mate Desktop"
            schema="org.mate.background"  
            key="picture-filename"
            ;;
        cinnamon) 
            echo "Cinnamon Desktop"
            schema="org.cinnamon.desktop.background"
            key="picture-uri"
            key_prefix='file://'
            ;;
        *) echo "[ERROR]: Desktop Environment NOT supported" >&2
            exit 1
            ;;
    esac
}
validate_dir(){
    if [ ! -d "$1" ]; then
        echo "The '$1' folder does not exist" 1>&2
        exit 1
    fi
}

get_random_theme(){
    file_path=$(find $wallpaper_dir_path -type f  | sort --random-sort | head --lines=1)
}

usage(){
    echo "Syntaxis: "
    printf "\t %s \n" "$(basename $0) [theme_folder]"
}

####### Main ########
#echo "Outside Function:" $bus_address
#export $bus_address

set_schema_key

validate_dir "$wallpaper_dir_path"
case $# in
    0) get_random_theme
        ;;
    1)  theme_folder="$1"
        wallpaper_dir_path="$wallpaper_dir_path/$theme_folder"
        validate_dir "$wallpaper_dir_path"
        get_random_theme
        ;;
    *) usage
        exit 1
        ;;
esac
#gsettings set org.mate.background picture-filename "$file_path"  
gsettings set "${schema}" "${key}" "${key_prefix}${file_path}"  
echo "Selected image: ${key_prefix}$file_path"
