#!/usr/bin/env bash
#### Add logic to install powerline from here
bud="${HOME}/vim_backup" # Back Up Directory
VIMDIR="${HOME}/.vim"
VIMCONFIG="${HOME}/.vim/vimrc"
GVIMCONFIG="${HOME}/.vim/gvimrc"
VIMSYMLINK="${HOME}/.vimrc"
GVIMSYMLINK="${HOME}/.gvimrc"
## TODO: Find out if the right vim is installed in the system
## TODO: IF current version does not work, modify ycm's repo-url to ycm-core
pushd ${HOME}
if [ -f ./.vimrc -a ! -d ${bud} ];then
    echo "Creating back up directory ..."
    until [ -d ${bud} -a ! -f ./.vimrc -a  ! -d ./.vim ];do
        mkdir ${bud}
        mv ./.vimrc ./.vim "${bud}"
    done
    echo "Done"
else
    echo " .vimrc does not exits or backup Folder already exists, terminating the script continuing ..."
fi
# if [ ! -d ${HOME}/.vim ]; then
## TODO: Find the way to make vim create its own .vim folder in case it does not 
## exists yet.
git clone https://github.com/JaghutTyrant/dotvim.git "${VIMDIR}"
ln -s -b "${VIMCONFIG}" "${VIMSYMLINK}" 
ln -s -b "${GVIMCONFIG}" "${GVIMSYMLINK}" 
pushd"$VIMDIR" 
git submodule update --init --recursive
install_ycm(){
    # Basic requirements
    # TODO: Update this vim-nox does not support clipboard
    sudo apt-get -y install build-essential cmake vim-nox python3-dev
    # Language specific requirements: golang, and nodejs+npm for javascript
    # and typescript support, I did not include requirements for C# and Java.
    sudo apt-get -y install golang nodejs npm
	pushd ${HOME}/.vim/bundle/YouCompleteMe
    ### Some submodules have themselves many submodules
    git submodule update --init --recursive
    ### TODO: may need to add here clang libraries for installation
    ## TODO: ycm does not seem to install on ubuntu20.04-based systems ...
	python3 install.py --clang-completer --clangd-completer --go-completer \
        --js-completer --ts-completer
	popd
}
# Commented with hyperx alloy origins core
install_ycm
popd
popd
