#!/usr/bin/env bash
#### Add logic to install powerline from here
bud="${HOME}/vim_backup" # Back Up Directory
## TODO: Find out if the right vim is installed in the system
## TODO: IF current version does not work, modify ycm's repo-url to ycm-core
pushd ${HOME}
if [ -f ./.vimrc -a ! -d ${bud} ];then
    echo "Creating back up directory ..."
    until [ -d ${bud} -a ! -f ./.vimrc -a  ! -d ./.vim ];do
        mkdir ${bud}
        mv ./.vimrc ./.vim "${bud}"
    done
    echo "Done"
else
    echo " .vimrc does not exits or backup Folder already exists, terminating the script continuing ..."
fi
# if [ ! -d ${HOME}/.vim ]; then
## TODO: Find the way to make vim create its own .vim folder in case it does not 
## exists yet.
git clone https://github.com/JaghutTyrant/dotvim.git "${HOME}/.vim"
ln -s -b ${HOME}/.vim/vimrc ${HOME}/.vimrc
ln -s -b ${HOME}/.vim/gvimrc ${HOME}/.gvimrc
pushd ${HOME}/.vim
git submodule update --init --recursive
installYCM(){
	# Ubuntu 16.04 and later
	sudo apt install build-essential cmake python3-dev 
	pushd ${HOME}/.vim/bundle/YouCompleteMe
    ### Some submodules have themselves many submodules
    git submodule update --init --recursive
    ### TODO: may need to add here clang libraries for installation
    ## TODO: ycm does not seem to install on ubuntu20.04-based systems ...
	python3 install.py --clang-completer
	popd
}
installYCM
popd
popd
