#!/usr/bin/env bash
#### Add logic to install powerline from here
bud="${HOME}/vim_backup" # Back Up Directory

pushd ${HOME}
if [[ -f ./.vimrc -a ! -d ${bud} ]];then
    echo "Creating back up directory ..."
    until [ -d ${bud} -a ! -f ./.vimrc -a  ! -d ./.vim ];do
        mkdir ${bud}
        mv ./.vimrc ./.vim "${bud}"
    done
    echo "Done"
else
    echo " .vimrc does not exits or backup Folder already exists, terminating the script continuing ..."
fi
git clone https://github.com/JaghutTyrant/dotvim.git "${HOME}/.vim"
ln -s -b ${HOME}/.vim/vimrc ${HOME}/.vimrc
ln -s -b ${HOME}/.vim/gvimrc ${HOME}/.gvimrc
pushd ${HOME}/.vim
git submodule update --init --recursive
installYCM(){
	# Ubuntu 16.04 and later
	sudo apt install build-essential cmake python3-dev 
	pushd ${HOME}/.vim/bundle/YouCompleteMe
	python3 install.py --clang-completer	
	popd
}
installYCM
popd
popd
