#!/bin/bash
##### VARIABLES
##### FUNCTIONS
clean(){
    sudo sysctl -w vm.drop_caches=3
    sudo sync && echo 3 | sudo tee /proc/sys/vm/drop_caches
}
usage(){
    program=$(basename $0)
    echo "Usage: $program"
}
####### Main
if [ $UID -ne 0 ]; then
   echo "Only root can execute this script" 1>&2
   exit 1
fi
if [ $# -ne 0 ]; then
   usage
   exit 1
fi

clean
