#!/bin/bash
add_repository(){
    sudo add-apt-repository ppa:videolan/stable-daily
}
install_vlc(){
    sudo apt-get update
    sudo apt-get install vlc vlc-plugin-* -y
    sudo apt-get install totem
}

################### MAIN ####################
if [ $(id -u) -ne 0 ];then
    echo "This script can only be executed by root";
    exit 1;
fi
add_repository
install_vlc
