#!/bin/bash
sudo apt-get install -y python-pip && sudo apt-get install -y python3-pip
sudo apt-get install -y python-dev python-pip python3-dev python3-pip
sudo apt-get install -y python-wheel
sudo apt-get install -y python-setuptools
sudo apt-get install -y python3-setuptools
sudo apt-get install -y python-pyqt4
sudo apt-get install -y python3-pyqt4
sudo apt-get install -y python3-pyqt5
sudo pip install paramiko
sudo pip3 install paramiko 
sudo pip install wheel
sudo pip3 install wheel
#sudo pip install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
#sudo pip3 install --user numpy scipy matplotlib ipython jupyter pandas sympy nose
sudo apt-get -y install python-tk
sudo pip install numpy scipy matplotlib ipython jupyter pandas sympy nose
sudo pip3 install numpy scipy matplotlib ipython jupyter pandas sympy nose
sduo pip install scapy
#### Deprecated, Now Scapy can be installed using pip
#inst_py_scapy(){
#    cd /tmp
#    wget -O scapy-latest.zip scapy.net
#    unzip scapy-latest.zip
#    cd scapy-2.*
#    sudo python setup.py install
#}
#inst_py_scapy
