#!/bin/bash
### Script to install tor browser form repository ###
list_file="/etc/apt/sources.list.d/tor_browser.list"
add_repo(){
    if [ -f $list_file ]; then sudo rm $list_file;fi
    sudo sh -c 'echo "deb http://deb.torproject.org/torproject.org trusty main" >> /etc/apt/sources.list.d/tor_browser.list'
    sudo sh -c 'echo "deb-src http://deb.torproject.org/torproject.org trusty main" >> \
     /etc/apt/sources.list.d/tor_browser.list'
}

add_key(){
    sudo gpg --keyserver keys.gnupg.net --recv 886DDD89
    sudo gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | sudo apt-key add -
}

install_tor(){
    sudo apt-get update
    sudo apt-get -y install tor deb.torproject.org-keyring
}
usage(){
    echo "Script to install tor-browser from the project's repository"
    echo "USAGE:"
    printf "\t%s\n" $(basename $0)
}
#### MAIN #####
if [ $# -ne 0 ]; then usage; exit 1;fi
add_repo && add_key && install_tor


